import frappe


def _insert_and_return(doc):
    """Insert a document returned by a core make_* function."""
    if not doc:
        frappe.throw("No document was generated by the conversion function.")

    if isinstance(doc, dict):
        doc = frappe.get_doc(doc)

    if doc.is_new():
        doc.insert(ignore_permissions=True)

    return doc


@frappe.whitelist()
def make_opportunity_and_insert(source_name, target_doc=None):
    """
    Create and insert Opportunity from Lead.

    Same signature as erpnext.crm.doctype.lead.lead.make_opportunity
    """
    if not frappe.db.exists("Lead", source_name):
        frappe.throw(f"Lead '{source_name}' does not exist.")

    doc = frappe.call(
        "erpnext.crm.doctype.lead.lead.make_opportunity",
        source_name=source_name,
        target_doc=target_doc,
    )

    opportunity = _insert_and_return(doc)
    return opportunity.name


@frappe.whitelist()
def make_quotation_and_insert(source_name, target_doc=None):
    """
    Create and insert Quotation from Opportunity.

    Same signature as erpnext.crm.doctype.opportunity.opportunity.make_quotation
    """
    if not frappe.db.exists("Opportunity", source_name):
        frappe.throw(f"Opportunity '{source_name}' does not exist.")

    doc = frappe.call(
        "erpnext.crm.doctype.opportunity.opportunity.make_quotation",
        source_name=source_name,
        target_doc=target_doc,
    )

    quotation = _insert_and_return(doc)
    return quotation.name


@frappe.whitelist()
def make_sales_order_and_insert(source_name, target_doc=None):
    """
    Create and insert Sales Order from Quotation.

    Same signature as erpnext.selling.doctype.quotation.quotation.make_sales_order
    """
    if not frappe.db.exists("Quotation", source_name):
        frappe.throw(f"Quotation '{source_name}' does not exist.")

    doc = frappe.call(
        "erpnext.selling.doctype.quotation.quotation.make_sales_order",
        source_name=source_name,
        target_doc=target_doc,
    )

    sales_order = _insert_and_return(doc)
    return sales_order.name
