import frappe
from frappe.utils import today


def _insert_and_return(doc):
    """
    Insert a document returned by a core make_* function,
    ensuring ERPNext-required defaults before insert.
    """
    if not doc:
        frappe.throw("No document was generated by the conversion function.")

    if isinstance(doc, dict):
        doc = frappe.get_doc(doc)

    if doc.is_new():
        ensure_defaults_before_insert(doc)
        doc.insert(ignore_permissions=True)

    return doc


def ensure_defaults_before_insert(doc):
    """
    Ensure mandatory defaults required by ERPNext validations
    are present before insert.
    """
    if doc.doctype == "Sales Order":
        ensure_sales_order_delivery_dates(doc)


def ensure_sales_order_delivery_dates(doc):
    """
    ERPNext requires a delivery_date on Sales Order header
    or per item. We normalize both to a safe default.
    """
    default_date = today()

    if not doc.delivery_date:
        doc.delivery_date = default_date

    for row in doc.items or []:
        if not row.delivery_date:
            row.delivery_date = doc.delivery_date


@frappe.whitelist()
def make_opportunity_and_insert(source_name, target_doc=None):
    """
    Create and insert Opportunity from Lead.

    Same signature as erpnext.crm.doctype.lead.lead.make_opportunity
    """
    if not frappe.db.exists("Lead", source_name):
        frappe.throw(f"Lead '{source_name}' does not exist.")

    doc = frappe.call(
        "erpnext.crm.doctype.lead.lead.make_opportunity",
        source_name=source_name,
        target_doc=target_doc,
    )

    opportunity = _insert_and_return(doc)
    return opportunity.name


@frappe.whitelist()
def make_quotation_and_insert(source_name, target_doc=None):
    """
    Create and insert Quotation from Opportunity.

    Same signature as erpnext.crm.doctype.opportunity.opportunity.make_quotation
    """
    if not frappe.db.exists("Opportunity", source_name):
        frappe.throw(f"Opportunity '{source_name}' does not exist.")

    doc = frappe.call(
        "erpnext.crm.doctype.opportunity.opportunity.make_quotation",
        source_name=source_name,
        target_doc=target_doc,
    )

    quotation = _insert_and_return(doc)
    return quotation.name


@frappe.whitelist()
def make_sales_order_and_insert(source_name, target_doc=None):
    """
    Create and insert Sales Order from Quotation.

    Same signature as erpnext.selling.doctype.quotation.quotation.make_sales_order
    """
    if not frappe.db.exists("Quotation", source_name):
        frappe.throw(f"Quotation '{source_name}' does not exist.")

    doc = frappe.call(
        "erpnext.selling.doctype.quotation.quotation.make_sales_order",
        source_name=source_name,
        target_doc=target_doc,
    )

    sales_order = _insert_and_return(doc)
    return sales_order.name
